# Generated by Django 5.1.5 on 2025-02-05 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('breed', models.CharField(max_length=300)),
                ('animal', models.CharField(max_length=300)),
                ('color', models.CharField(max_length=300)),
                ('age', models.IntegerField()),
                ('description', models.CharField(max_length=650, null=True)),
                ('image', models.CharField(max_length=300)),
                ('gender', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=650, null=True)),
                ('phone', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctorid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=250)),
                ('qualification', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('animal', models.CharField(max_length=300)),
                ('producttype', models.CharField(max_length=300)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('serviceid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('cost', models.IntegerField()),
                ('time', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('petid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=300)),
                ('animal', models.CharField(max_length=300)),
                ('breed', models.CharField(max_length=300)),
                ('color', models.CharField(max_length=300)),
                ('customer_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='petwell.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('hid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=650, null=True)),
                ('prescription', models.CharField(max_length=650, null=True)),
                ('customer_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='petwell.customer')),
                ('pet_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='petwell.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('slot', models.CharField(max_length=300)),
                ('booking_type', models.CharField(max_length=300)),
                ('customer_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='petwell.customer')),
                ('doctor_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='petwell.doctor')),
                ('pet_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='petwell.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchaseid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('paid', models.BooleanField(default=False)),
                ('delivery_status', models.CharField(max_length=300)),
                ('customer_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='petwell.customer')),
                ('product_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='petwell.product')),
            ],
        ),
        migrations.CreateModel(
            name='Petservice',
            fields=[
                ('pserviceid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=300)),
                ('customer_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='petwell.customer')),
                ('pet_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='petwell.pet')),
                ('service_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='petwell.service')),
            ],
        ),
    ]
