# Generated by Django 5.1.5 on 2025-02-05 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petwell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='aproved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=250)),
                ('product_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='petwell.product')),
            ],
        ),
    ]
