# Generated by Django 5.1.5 on 2025-02-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petwell', '0002_product_aproved_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctorid',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
