# Generated by Django 5.1.5 on 2025-02-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petwell', '0003_alter_doctor_doctorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctorid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
