# Generated by Django 5.1.5 on 2025-02-06 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petwell', '0004_alter_doctor_doctorid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='seller_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='petwell.seller'),
        ),
    ]
