# Generated by Django 5.1.7 on 2025-03-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petwell', '0005_remove_seller_product_id_product_seller_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='aproved',
            new_name='approved',
        ),
        migrations.AddField(
            model_name='adoption',
            name='adopted',
            field=models.BooleanField(default=False),
        ),
    ]
