# Generated by Django 5.1.5 on 2025-03-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petwell', '0006_rename_aproved_product_approved_adoption_adopted'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/pics/img1.jpg', upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adoption',
            name='image',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
