# Generated by Django 5.1.5 on 2025-03-23 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petwell', '0007_product_image_alter_adoption_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='paid',
            new_name='payed',
        ),
    ]
