# Generated by Django 5.1.7 on 2025-03-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petwell', '0008_rename_paid_purchase_payed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.CharField(max_length=650, null=True),
        ),
    ]
