# Generated by Django 5.1.7 on 2025-03-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petwell', '0009_alter_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_for',
            field=models.CharField(default='Grooming', max_length=300),
            preserve_default=False,
        ),
    ]
