# Generated by Django 5.1.5 on 2025-03-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petwell', '0010_booking_booked_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='date',
            field=models.CharField(max_length=650, null=True),
        ),
    ]
