# Generated by Django 5.1.5 on 2025-03-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petwell', '0011_alter_health_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='phone',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
