# Generated by Django 5.1.7 on 2025-03-30 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petwell', '0012_adoption_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='customer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='petwell.customer'),
        ),
    ]
