# Generated by Django 5.1.5 on 2025-04-05 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petwell', '0013_adoption_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='quantity',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.CharField(max_length=650, null=True),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=650, null=True)),
                ('customer_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='petwell.customer')),
                ('product_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='petwell.product')),
            ],
        ),
    ]
